spring:
  datasource:
    url: jdbc:mysql://localhost:6033/kin_pet_store_db?allowPublicRetrieval=true&useSSL=false
    username: KIN_PET_STORE_USER
    password: KIN_PET_STORE_PASSWORD
  jpa:
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: TAv8e7KkbquKYS9jL0rOLp9ZPOR7Y6t9
            client-secret: Rezs-STJ049Vz_OoPIiSl9HFX9xOCwOBGkzg9Lwnbf_1BqjHbBqHkhkBdi-jEfJ3
            scope:
              - openid
              - profile
              - email
            redirectUri: http://127.0.0.1:8080/login/oauth2/authorize
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-ig-automation.jp.auth0.com/
            jwk-set-uri: https://dev-ig-automation.jp.auth0.com/.well-known/jwks.json
      resourceserver:
        jwt:
          issuer-uri: https://dev-ig-automation.jp.auth0.com/
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

auth0:
  audience: https://127.0.0.1:8080/api/v1/